import type { NextPage } from 'next'
import { getImageSize } from 'next/dist/server/image-optimizer'
import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react'
import apiFetch from '../lib/apiFetch'

type fetchData = {
  data: string;
}

let fileHandle;

const Automaton_download: NextPage = () => {
  const site = 'http://37.44.209.11/snap.jpeg';
  const [image, setImage] = useState<string>();

  const apiurl = '/api/download-resource';

  const fileSelector = async () => {
    [fileHandle] = await window.showOpenFilePicker();

    const file = await fileHandle.getFile();
    const content = await file.text();

    return content;
  };

  const getImage = () => {
    apiFetch<fetchData>(apiurl, {})
      .then(response => {

        setImage(response.data);
        console.log("response");
        console.log(response);
        // myimage = response
      })
      .catch(err => console.log(err)
      )
    // const response = fetch(site);
    // console.log(response);
    // console.log(image);

    // setImage()
  }
  // let myimage: string;

  // fetch(apiurl)
  useEffect(() => {
    getImage();
  }, []);

  // fetch(apiurl, {
  //   headers: {
  //     'Content-Type': 'application/json'
  //   },
  //   method: 'POST'
  // })

  // .then((res) => res.json())
  // .then(response => {

  //   // console.log(response);
  //   setImage("response");
  //   console.log("response");
  //   // myimage = response
  // })

  return (
    <div className={""}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <button onClick={getImage} className='bg-black text-white p-2 rounded-md m-2'>reload</button>
      <div className='border-2 w-10 h-10'>
        {/* {image} */}
        {image &&
          <Image src={image} alt="me" width="500px" height="500px" />
        }
      </div>

      <button onClick={fileSelector} className='bg-black text-white p-2 rounded-md m-2'>choose file</button>
    </div>
  );
}

export default Automaton_download;